const fs = require('fs');
const out = [];
out.push("export const romanHikayeSorulari = [");
function q(id,s,o,z,b){out.push("  { id: '"+id+"', soru: '"+s+"', secenekler: ['"+o[0]+"', '"+o[1]+"', '"+o[2]+"', '"+o[3]+"'], dogruCevap: 0, kategori: 'Roman & Hikaye', zorluk: '"+z+"', bilgi: '"+b+"' },");}
function sec(c){out.push("");out.push("  // "+("=".repeat(60)));out.push("  // "+c);out.push("  // "+("=".repeat(60)));}
sec("COK KOLAY (50 soru - rh001 - rh050)");
var ck=[
["rh001","Askin Memnu romaninin yazaridir?",["Halid Ziya Usakligil","Resat Nuri Guntekin","Yakup Kadri Karaosmanoglu","Sabahattin Ali"],"cokKolay","Askin Memnu, Servet-i Funun doneminin en onemli romanidir."],
["rh002","Calikusu romaninin bas kahramani kimdir?",["Feride","Bihter","Nurullah","Adnan"],"cokKolay","Calikusunun baskahramani Feride ogretmendir."],
["rh003","Mai ve Siyah romanini hangi edebi akim ortaya cikarmistir?",["Servet-i Funun","Milli Edebiyat","Tanzimat","Cumhuriyet"],"cokKolay","Mai ve Siyah, Servet-i Funun akiminin onemli eseridir."],
["rh004","Orhan Pamuk hangi uluslararasi odulu kazanmistir?",["Nobel Edebiyat Odulu","Pulitzer Odulu","Man Booker Odulu","Goncourt Odulu"],"cokKolay","Orhan Pamuk, 2006 yilinda Nobel Edebiyat Odulunu almistir."],
["rh005","Sait Faik Abasiyanik hangi turde eserler yazmistir?",["Hikaye","Roman","Siir","Tiyatro"],"cokKolay","Sait Faik, Turk edebiyatinin en onemli hikaye yazaridir."],
["rh006","Intibah romani hangi donemde yazilmistir?",["Tanzimat","Servet-i Funun","Milli Edebiyat","Cumhuriyet"],"cokKolay","Intibah, Tanzimat doneminin ilk romanidir."],
["rh007","Kurk Mantolu Madonna romaninin yazaridir?",["Sabahattin Ali","Peyami Safa","Yakup Kadri Karaosmanoglu","Halikarnas Balikcisi"],"cokKolay","Kurk Mantolu Madonna, Sabahattin Alinin unlu romanidir."],
["rh008","Yaban romaninin yazaridir?",["Yakup Kadri Karaosmanoglu","Resat Nuri Guntekin","Halid Ziya Usakligil","Sabahattin Ali"],"cokKolay","Yaban, Yakup Kadri Karaosmanoglu nun onemli romanidir."],
["rh009","Ince Memed romaninin yazaridir?",["Yasar Kemal","Orhan Kemal","Sabahattin Ali","Peyami Safa"],"cokKolay","Ince Memed, Yasar Kemalin unlu romanidir."],
["rh010","Askin Memnunun bas kahramani kimdir?",["Bihter","Feride","Nurullah","Adnan"],"cokKolay","Askin Memnuda Bihter basroldedir."],
["rh011","Tanzimat edebiyatinin ilk romani hangisidir?",["Intibah","Tasuk-i Talat ve Fitnat","Felatun Bey ile Rakim Efendi","Huzun"],"cokKolay","Intibah, ilk Turk romanidir."],
["rh012","Askin Memnuda Bihter ile Behlul arasindaki iliski nasildir?",["Yasak ask","Platonik ask","Esler arasi ask","Kardeslik"],"cokKolay","Roman yasak ask iliskisini anlatir."],
["rh013","Calikusunun Feridesi hangi meslegi yapar?",["Ogretmenlik","Hekimlik","Avukatlik","Muhendislik"],"cokKolay","Feride Anadolu koylerinde ogretmenlik yapar."],
["rh014","Mai ve Siyahta Ahmet Cemil hangi idealin pesindedir?",["Sanatci olmak","Zengin olmak","Memur olmak","Asker olmak"],"cokKolay","Ahmet Cemil sanatci olmak istemektedir."],
["rh015","Orhan Pamukun Benim Adim Kirmizi romani hangi konuyu isler?",["Minyatur sanati","Osmanli tarihi","Modern Istanbul","Koy hayati"],"cokKolay","Benim Adim Kirmizi, Osmanli minyatur sanatini konu alir."],
["rh016","Sait Faikin Son Kuslar hikayesinin kahramani kimdir?",["Himmet Aga","Hasan","Mehmet","Ali"],"cokKolay","Son Kuslar hikayesinin kahramani Himmet Agadir."],
["rh017","Yaban romaninda koyun adi nedir?",["Sariyer","Bursa","Ankara","Istanbul"],"cokKolay","Roman Sariyer koyunde gecer."],
["rh018","Kurk Mantolu Mannadada Raif Efendi hangi meslegi yapar?",["Tercumanlik","Hekimlik","Ogretmenlik","Avukatlik"],"cokKolay","Raif Efendi tercumanlik yapmaktadir."],
["rh019","Intibah romaninda Ali Beyin sevdigi kadin kimdir?",["Mehpeyker","Nefise","Zeynep","Fatma"],"cokKolay","Ali Bey Mehpeykere asiktir."],
["rh020","Servet-i Fununda Funun ne anlama gelir?",["Bilimler","Sanatlar","Edebiyat","Felsefe"],"cokKolay","Funun Arapcada bilimler anlamina gelir."],
["rh021","Calikusunun Feridesi hangi sehrde ogretmenlik yapar?",["Anadolu koyleri","Istanbul","Izmir","Ankara"],"cokKolay","Feride Anadolu koylerinde ogretmenlik yapar."],
["rh022","Oguz Atayin Tutunamayanlar romaninin baskahramani kimdir?",["Selim Isik","Ahmet Cemil","Raif Efendi","Nurullah"],"cokKolay","Tutunamayanlarda Selim Isik baskahramandir."],
["rh023","Sabahattin Ali hangi romaninda Almanyayi anlatir?",["Kurk Mantolu Madonna","Icimizdeki Seytan","Kuyucakli Yusuf","Sefiller"],"cokKolay","Kurk Mantolu Mannadada Almanyada gecen bir hikaye anlatilir."],
["rh024","Halide Edib Adivarin Vurun Kahpeye romani hangi donemi anlatir?",["Kurtulus Savasi","Tanzimat","II. Mesrutiyet","Cumhuriyet"],"cokKolay","Vurun Kahpeye Kurtulus Savasi donemini anlatir."],
["rh025","Yakup Kadri Karaosmanoglu nun Yaban romani hangi konuyu isler?",["Koy-sehir catisma","Ask hikayesi","Tarihi olaylar","Polisiye"],"cokKolay","Yaban koy-sehir catisma temasini isler."],
["rh026","Peyami Safanin Dokuzuncu Hariciye Kogusu hangi konuyu isler?",["Hastalik ve ask","Savas","Is hayati","Siyaset"],"cokKolay","Dokuzuncu Hariciye Kogusu hastalik ve aski anlatir."],
["rh027","Orhan Kemalin romanlari hangi konuyu isler?",["Isci hayati","Askerlik","Egitim","Siyaset"],"cokKolay","Orhan Kemal isci hayatinianlatir."],
["rh028","Memduh Sevket Esendalin hikayelerinin ozelligi nedir?",["Ince gozlem","Tarihi konular","Fantastik ogeler","Polisiye"],"cokKolay","Esendal gunluk hayattan ince gozlemler aktarir."],
["rh029","Ahmet Hamdi Tanpinarin Saati Ayarlama Enstitusu hangi konuyu isler?",["Modernlesme","Ask","Savas","Koy hayati"],"cokKolay","Saati Ayarlama Enstitusu modernlesme surecini anlatir."],
["rh030","Halikarnas Balikcisi hangi sehri edebiyatina tasimistir?",["Bodrum","Istanbul","Izmir","Antalya"],"cokKolay","Halikarnas Balikcisi Bodrumu edebiyatina tasimistir."],
["rh031","Necip Fazil Kisakurek hangi romaniyla taninir?",["Organize Seytanlar","Tutunamayanlar","Kurk Mantolu Madonna","Ince Memed"],"cokKolay","Organize Seytanlar Kisakurekin onemli romanidir."],
["rh032","Suat Dervisin Fren Gemisi hangi konuyu isler?",["Kadin sorunlari","Savas","Tarih","Doga"],"cokKolay","Fren Gemisi kadin sorunlarini isler."],
["rh033","Tanzimat romaninin temel amaci nedir?",["Toplumsal reform","Eglence","Tarih yazimi","Din propagandasi"],"cokKolay","Tanzimat romanlari toplumsal reformu amaclamistir."],
["rh034","Askin Memnuda Adnan Bey kiminle evlidir?",["Bihter","Feride","Nefise","Zeynep"],"cokKolay","Adnan Bey Bihter ile evlidir."],
["rh035","Mai ve Siyahta Lemercier hangi ulkedendir?",["Fransa","Ingiltere","Almanya","Italya"],"cokKolay","Lemercier Fransiz bir karakterdir."],
["rh036","Calikusunda Feride ile Kamuran arasindaki iliski nasildir?",["Sevgili","Kardes","Dost","Rakip"],"cokKolay","Feride ile Kamuran sevgilidir."],
["rh037","Yaban romaninda Mehmet Bey hangi gorevi yapar?",["Koy ogretmeni","Doktor","Avukat","Muhendis"],"cokKolay","Mehmet Bey koy ogretmenidir."],
["rh038","Sabahattin Alinin Kuyucakli Yusuf romani hangi konuyu isler?",["Ask ve toplumsal sorunlar","Savas","Siyaset","Bilim"],"cokKolay","Kuyucakli Yusuf ask ve toplumsal sorunlari isler."],
["rh039","Orhan Pamukun Kar romani hangi sehirde gecer?",["Kars","Istanbul","Ankara","Izmir"],"cokKolay","Kar romani Karssta gecmektedir."],
["rh040","Yasar Kemalin Ince Memedinde baskahraman hangi tur characterdir?",["Eskiiya","Ogretmen","Doktor","Asker"],"cokKolay","Ince Memed bir eskiiya characteridir."],
["rh041","Kiralik Konakta hangi semt anlatilir?",["Galata","Sultanahmet","Beyoglu","Uskudar"],"cokKolay","Kiralik Konak Galata semtini anlatir."],
["rh042","Askin Memnuda Nihal kiz kime aittir?",["Adnan Bey","Behlul","Bulent","Matmazel"],"cokKolay","Nihal Adnan Beyin kizidir."],
["rh043","Servet-i Funun akimi hangi ulkenin etkisiyle gelisti?",["Fransa","Ingiltere","Almanya","Rusya"],"cokKolay","Servet-i Funun Fransiz edebiyatinin etkisinde gelisti."],
["rh044","Intibah romaninda Ali Bey hangi aileden gelir?",["Zengin bir aile","Fakir bir aile","Asil bir aile","Koylu bir aile"],"cokKolay","Ali Bey zengin bir aileden gelmektedir."],
["rh045","Calikusu romani hangi turredir?",["Romantik","Polisiye","Tarihi","Bilimsel"],"cokKolay","Calikusu romantik bir romandir."],
["rh046","Orhan Pamukun Sessiz Ev romani hangi konuyu isler?",["Aile ici iliskiler","Savas","Siyaset","Ekonomi"],"cokKolay","Sessiz Ev aile ici iliskileri anlatir."],
["rh047","Sait Faikin hikayelerinde hangi sehrde gecer?",["Istanbul","Ankara","Izmir","Bursa"],"cokKolay","Sait Faikin hikayeleri Istanbulda gecer."],
["rh048","Halid Ziya Usakligil hangi akimin kurucusudur?",["Servet-i Funun","Milli Edebiyat","Tanzimat","Garip"],"cokKolay","Halid Ziya Usakligil Servet-i Fununun kurucusudur."],
["rh049","Kurk Mantolu Mannadada Maria Puder hangi ulkedendir?",["Almanya","Fransa","Italya","Avusturya"],"cokKolay","Maria Puder Almanyali bir kadindir."],
["rh050","Tanzimatin ilk romani olan Intibahta hangi tema islenir?",["Egitim ve ahlak","Savas","Ask","Siyaset"],"cokKolay","Intibahta egitim ve ahlak temasii islenir."]
];
ck.forEach(r=>q(r[0],r[1],r[2],r[3],r[4]));
sec("KOLAY (100 soru - rh051 - rh150)");
var kol=[
["rh051","Askin Memnuda Behlul ile Bihterin aski nasil sonuclanir?",["Evlilik","Ayrilik","Hosuma","Tragedya"],"kolay","Roman yasak askin trajik sonucunu anlatir."],
["rh052","Calikusunda Feride ile Kamuran hangi sehirde tanisir?",["Istanbul","Ankara","Izmir","Bursa"],"kolay","Feride ile Kamuran Istanbulda tanisir."],
["rh053","Mai ve Siyahta Ahmet Cemil hangi sinavi kaybeder?",["Tibbiye sinavi","Mulkiye sinavi","Harbiye sinavi","Hukuk sinavi"],"kolay","Ahmet Cemil Tibbiye sinavini kaybeder."],
["rh054","Orhan Pamukun Benim Adim Kirmizi romani hangi yilda yayimlanmistir?",["1998","2002","2006","2010"],"kolay","Benim Adim Kirmizi 1998 yilinda yayimlanmistir."],
["rh055","Sabahattin Ali hangi romanini koy hayati icin yazmistir?",["Kurk Mantolu Madonna","Kuyucakli Yusuf","Icimizdeki Seytan","Sefiller"],"kolay","Kuyucakli Yusuf koy hayati hakkindadir."],
["rh056","Yaban romaninda koy ogretmeni kimdir?",["Mehmet Bey","Ali Riza Bey","Hasan Aga","Ahmet Bey"],"kolay","Mehmet Bey koy ogretmenidir."],
["rh057","Kurk Mantolu Mannadada Raif Efendi hangi meslegi yapar?",["Tercumanlik","Hekimlik","Ogretmenlik","Avukatlik"],"kolay","Raif Efendi tercumanlik yapmaktadir."],
["rh058","Intibah romaninda Ali Beyin sevdigi kadin kimdir?",["Mehpeyker","Nefise","Zeynep","Fatma"],"kolay","Ali Bey Mehpeykere asiktir."],
["rh059","Servet-i Fununun kapanis yili hangisidir?",["1901","1910","1920","1930"],"kolay","Servet-i Funun 1901 yilinda kapanmistir."],
["rh060","Calikusunda Feride neden Anadolu koylerine gider?",["Gonullu olarak","Mecburen","Zenginlik icin","Aile baskisi"],"kolay","Feride gonullu olarak Anadolu koylerine gider."],
["rh061","Oguz Atayin Tutunamayanlar romani hangi turde yazilmistir?",["Postmodern","Modern","Realist","Romantik"],"kolay","Tutunamayanlar postmodern bir romandir."],
["rh062","Sait Faikin hikayelerinde hangi semt on cikar?",["Heybeliada","Beyoglu","Kadikoy","Uskudar"],"kolay","Sait Faikin hikayelerinde Heybeliada on cikar."],
["rh063","Askin Memnuda Behlul Adnan Beyin kacinci nesli sayilir?",["Yejen","Oglu","Kardesi","Dayisi"],"kolay","Behlul Adnan Beyin yejenidir."],
["rh064","Mai ve Siyahta Cemil hangi duygu icindedir?",["Umutsuzluk","Sevinc","Korku","Ofeke"],"kolay","Cemil umutsuzluk icindedir."],
["rh065","Resat Nuri Guntekin hangi romaniyla taninir?",["Calikusu","Yaban","Kiralik Konak","Ince Memed"],"kolay","Resat Nuri Guntekin Calikusu ile taninir."],
["rh066","Yakup Kadri Karaosmanoglu nun Yaban romani hangi yilda yayimlanmistir?",["1932","1935","1940","1945"],"kolay","Yaban 1932 yilinda yayimlanmistir."],
["rh067","Sabahattin Ali hangi romaninda aski anlatir?",["Kurk Mantolu Madonna","Icimizdeki Seytan","Kuyucakli Yusuf","Sefiller"],"kolay","Kurk Mantolu Madonna ask konusunu isler."],
["rh068","Orhan Pamukun Kar romani hangi konuyu isler?",["Siir ve siyaset","Ask","Savas","Ekonomi"],"kolay","Kar romaninda siir ve siyaset islenir."],
["rh069","Peyami Safa hangi romaninda Istanbulu anlatir?",["Dokuzuncu Hariciye Kogusu","Fatih-Harbiye","Cingoz Recai","Bizde Ikinclidir"],"kolay","Fatih-Harbiye Istanbulu anlatir."],
["rh070","Halide Edib Adivarin romanlarinda hangi konuyu isler?",["Kadin haklari","Savas","Ask","Doga"],"kolay","Halide Edibin romanlarinda kadin haklari on plandadir."],
["rh071","Ahmet Hamdi Tanpinarin romanlarinda hangi sehir on cikar?",["Istanbul","Ankara","Izmir","Konya"],"kolay","Tanpinarin romanlarinda Istanbul on cikar."],
["rh072","Orhan Kemal hangi romaninda isci hayatini anlatir?",["Bereketli Topraklar Uzerinde","Murtaza","Cevizli Sucuk","Tersine Dunya"],"kolay","Bereketli Topraklar Uzerinde isci hayatinianlatir."],
["rh073","Halikarnas Balikcisi hangi sehri edebiyatinda one cikarir?",["Bodrum","Istanbul","Izmir","Antalya"],"kolay","Halikarnas Balikcisi Bodrumu edebiyatinda one cikarir."],
["rh074","Necip Fazil Kisakurek hangi akima mensuptur?",["Islamci","Milliyetci","Sosyalist","Liberal"],"kolay","Necip Fazil Kisakurek Islamci bir yazardir."],
["rh075","Suat Dervis hangi turde yazarlik yapmistir?",["Hikaye","Roman","Siir","Tiyatro"],"kolay","Suat Dervis hikaye ve roman yazmistir."],
["rh076","Askin Memnuda Bihter hangi characterla evlenir?",["Adnan Bey","Behlul","Bulent","Matmazel"],"kolay","Bihter Adnan Bey ile evlenir."],
["rh077","Mai ve Siyahta Cemil hangi okulda okur?",["Tibbiye","Mulkiye","Harbiye","Hukuk"],"kolay","Cemil Tibbiyede okumaktadir."],
["rh078","Calikusunda Feride hangi okuldan mezun olur?",["Fransiz Kiz Lisesi","Istanbul Universitesi","Ankara Lisesi","Izmir Lisesi"],"kolay","Feride Fransiz Kiz Lisesinden mezun olur."],
["rh079","Yaban romaninda hangi yillar anlatilir?",["1920ler","1950ler","1880ler","1900ler"],"kolay","Yaban 1920li yillarda gecmektedir."],
["rh080","Orhan Pamukun Masumiyet Muzesi hangi yilda yayimlanmistir?",["2008","1998","2018","2010"],"kolay","Masumiyet Muzesi 2008 yilinda yayimlanmistir."],
["rh081","Sabahattin Ali hangi romaninda Anadoluyu dolasir?",["Kurk Mantolu Madonna","Kuyucakli Yusuf","Icimizdeki Seytan","Sefiller"],"kolay","Kurk Mantolu Mannadada Anadolu gezi anlatilir."],
["rh082","Yakup Kadri Karaosmanoglu nun Sodom ve Gomore romani hangi konuyu isler?",["Istanbulun cukurmesi","Ask","Savas","Koy hayati"],"kolay","Sodom ve Gomore Istanbulun cukurmuslugunu anlatir."],
["rh083","Orhan Kemalin Cevizli Sucuk romani hangi konuyu isler?",["Isci hayati","Savas","Ask","Siyaset"],"kolay","Cevizli Sucuk isci hayatinianlatir."],
["rh084","Peyami Safanin Bizde Ikinclidir romani hangi konuyu isler?",["Egitim","Ask","Savas","Siyaset"],"kolay","Bizde Ikinclidir egitim konusunu isler."],
["rh085","Sait Faikin Sahmerdan hikayesinin kahramani kimdir?",["Hasan","Mehmet","Ali","Ahmet"],"kolay","Sahmerdan hikayesinin kahramani Hasandir."],
["rh086","Ahmet Hamdi Tanpinarin Saatleri Ayarlama Enstitusu hangi yilda yayimlanmistir?",["1961","1951","1971","1981"],"kolay","Saatleri Ayarlama Enstitusu 1961 yilinda yayimlanmistir."],
["rh087","Halikarnas Balikcisinin Ege Kiyilarindan kitabi hangi turdur?",["Hikaye","Roman","Siir","Deneme"],"kolay","Ege Kiyilarindan bir hikaye kitabidir."],
["rh088","Necip Fazil Kisakurekin Bir Adam Yaratmak romani hangi konuyu isler?",["Islamci mukaveme","Ask","Savas","Siyaset"],"kolay","Bir Adam Yaratmak Islamci mukavemeti anlatir."],
["rh089","Suat Dervisin romanlarinda hangi tema islenir?",["Kadin sorunlari","Savas","Tarih","Doga"],"kolay","Suat Dervisin romanlarinda kadin sorunlari islenir."],
["rh090","Tanzimat romaninda hangi dil kullanilmistir?",["Osmanlica","Istanbul Turkcesi","Anadolu Turkcesi","Farsca"],"kolay","Tanzimat romanlarinda Osmanlica kullanilmistir."],
["rh091","Askin Memnuda Adnan Bey kac yasinda evlenir?",["Yasli","Genc","Cocuk","Yasli degil"],"kolay","Adnan Bey yasliyken Bihter ile evlenir."],
["rh092","Mai ve Siyahta Cemilin arkadasi kimdir?",["Lemercier","Behlul","Raif","Ali"],"kolay","Cemilin arkadasi Lemercierdir."],
["rh093","Calikusunda Feridenin annesi kimdir?",["Zeynep Hanim","Nefise","Fatma","Ayse"],"kolay","Feridenin annesi Zeynep Hanimdir."],
["rh094","Yaban romaninda Mehmet Bey hangi yillarda koyde calisir?",["1920ler","1950ler","1880ler","1900ler"],"kolay","Mehmet Bey 1920li yillarda koyde calisir."],
["rh095","Orhan Pamukun Kirmizi Sacli Kadin romani hangi konuyu isler?",["Su kuyuculugu","Ask","Savas","Siyaset"],"kolay","Kirmizi Sacli Kadin su kuyuculugu konusunu isler."],
["rh096","Sabahattin Ali hangi romaninda koy ogretmenini anlatir?",["Kuyucakli Yusuf","Kurk Mantolu Madonna","Icimizdeki Seytan","Sefiller"],"kolay","Kuyucakli Yusuf koy ogretmenini anlatir."],
["rh097","Halide Edib Adivarin hangi romani Ingilizce yazilmistir?",["Conflict of East and West","Vurun Kahpeye","Turk Agaclari","Son Eseri"],"kolay","Conflict of East and West Ingilizce yazilmistir."],
["rh098","Resat Nuri Guntekin hangi romaniyla taninir?",["Calikusu","Yaban","Kiralik Konak","Ince Memed"],"kolay","Resat Nuri Guntekin Calikusu ile taninir."],
["rh099","Askin Memnuda Behlul kac yasindadir?",["Genc","Yasli","Cocuk","Orta yasli"],"kolay","Behlul genc bir karakterdir."],
["rh100","Orhan Pamukun Cevdet Bey ve Ongullari romani hangi konuyu isler?",["Ticaret ailesi","Savas","Ask","Siyaset"],"kolay","Cevdet Bey ve Ongullari bir ticaret ailesini anlatir."],
["rh101","Mai ve Siyahta Cemilin hayali nedir?",["Ressam olmak","Doktor olmak","Asker olmak","Avukat olmak"],"kolay","Cemilin hayali ressam olmaktir."],
["rh102","Intibah romaninda Mehpeyker hangi karakterdir?",["Fahiye","Noble kadin","Ogretmen","Kralice"],"kolay","Mehpeyker Intibahta fahiye karakteridir."],
["rh103","Yakup Kadri Karaosmanoglu nun Ankara romani hangi konuyu isler?",["Baskentin kurulusu","Ask","Savas","Ekonomi"],"kolay","Ankara romani baskentin kurulusunu anlatir."],
["rh104","Peyami Safanin romanlarinda hangi tema islenir?",["Batilasma","Ask","Savas","Doga"],"kolay","Peyami Safanin romanlarinda batilasma temasii islenir."],
["rh105","Sait Faikin Tuneldeki Cocuk hikayesinin konusu nedir?",["Yoksulluk","Zenginlik","Ask","Savas"],"kolay","Tuneldeki Cocuk yoksulluk konusunu isler."],
["rh106","Memduh Sevket Esendalin Ayasli ve Kiracilari hikayesinin kahramani kimdir?",["Ayasli","Mehmet","Ali","Hasan"],"kolay","Ayasli ve Kiracilarinin kahramani Ayaslidir."],
["rh107","Halikarnas Balikcisi hangi yilda dogmustur?",["1886","1900","1920","1940"],"kolay","Halikarnas Balikcisi 1886 yilinda dogmustur."],
["rh108","Ahmet Hamdi Tanpinarin Mahur Beste romani hangi konuyu isler?",["Musiki","Savas","Ask","Siyaset"],"kolay","Mahur Beste musiki konusunu isler."],
["rh109","Yasar Kemal hangi romaniyla Varmak Roman Armaaganini kazanmistir?",["Ince Memed","Yaban","Calikusu","Askin Memnu"],"kolay","Yasar Kemal Ince Memed ile armaagani kazanmistir."],
["rh110","Sabahattin Alinin Kurk Mantolu Madonnasi hangi yilda yayimlanmistir?",["1938","1928","1948","1958"],"kolay","Kurk Mantolu Madonna 1938 yilinda yayimlanmistir."],
["rh111","Orhan Pamukun Benim Adim Kirmizi hangi odul kazanmistir?",["Prix du Meilleur Livre Etranger","Nobel","Pulitzer","Man Booker"],"kolay","Benim Adim Kirmizi Fransiz edebiyat odulunu kazanmistir."],
["rh112","Tanzimat edebiyatinda hangi tur romanlar daha cok yazilmistir?",["Tophane romanlari","Ask romanlari","Savas romanlari","Polisiye romanlar"],"kolay","Tanzimatta tophane romanlari yaygin olmustur."],
["rh113","Oguz Atayin Korkuyu Beklerken hangi turde eserdir?",["Hikaye","Roman","Siir","Deneme"],"kolay","Korkuyu Beklerken Oguz Atayin hikaye kitabidir."],
["rh114","Sait Faikin bir hikayesindeki balikci hangi yasi yasar?",["Yasli","Genc","Cocuk","Orta yasli"],"kolay","Sait Faikin hikayelerinde farkli yaslar anlatilir."],
["rh115","Halide Edib Adivarin Turk Agaclari romani hangi konuyu isler?",["Milli mucadele","Ask","Savas","Doga"],"kolay","Turk Agaclari milli mucadeleyi anlatir."],
["rh116","Resat Nuri Guntekinin Kizil Gul romani hangi konuyu isler?",["Ask","Savas","Siyaset","Ekonomi"],"kolay","Kizil Gul ask konusunu isler."],
["rh117","Servet-i Funun dergisinde hangi tur eserler yayimlanmistir?",["Roman ve hikaye","Sadece siir","Sadece tiyatro","Sadece deneme"],"kolay","Servet-i Fununda roman ve hikayeler yayimlanmistir."],
["rh118","Intibah romaninda Ali Beyin babasinin adi nedir?",["Seyyid Ahmed Pasa","Mehmet Pasa","Ali Pasa","Osman Pasa"],"kolay","Ali Beyin babasi Seyyid Ahmed Pasadir."],
["rh119","Mai ve Siyahta Cemil hangi okulda okur?",["Tibbiye","Mulkiye","Harbiye","Hukuk"],"kolay","Cemil Tibbiyede okur."],
["rh120","Calikusunda Feride ile Kamuran nerede tanisir?",["Istanbul","Ankara","Izmir","Bursa"],"kolay","Feride ile Kamuran Istanbulda tanisir."],
["rh121","Orhan Pamukun Masumiyet Muzesi hangi yilda yayimlanmistir?",["2008","1998","2018","2010"],"kolay","Masumiyet Muzesi 2008 yilinda yayimlanmistir."],
["rh122","Sabahattin Ali hangi romaninda Anadoluyu dolasir?",["Kurk Mantolu Madonna","Kuyucakli Yusuf","Icimizdeki Seytan","Sefiller"],"kolay","Kurk Mantolu Mannadada Anadolu gezi anlatilir."],
["rh123","Yakup Kadri Karaosmanoglu nun Sodom ve Gomore romani hangi yilda yazilmistir?",["1920","1928","1935","1940"],"kolay","Sodom ve Gomore 1928 yilinda yazilmistir."],
["rh124","Orhan Kemalin Cevizli Sucuk romani hangi yilda yazilmistir?",["1950","1955","1960","1965"],"kolay","Cevizli Sucuk 1950 yilinda yazilmistir."],
["rh125","Peyami Safanin romanlarinda hangi sehir on cikar?",["Istanbul","Ankara","Izmir","Bursa"],"kolay","Peyami Safanin romanlarinda Istanbul on cikar."],
["rh126","Sait Faikin Sahmerdan hikayesinin kahramani hangi meslegi yapar?",["Balikci","Ogretmen","Doktor","Avukat"],"kolay","Sahmerdan hikayesinin kahramani balikcidir."],
["rh127","Ahmet Hamdi Tanpinarin Saatleri Ayarlama Enstitusu hangi konuyu isler?",["Modernlesme","Ask","Savas","Koy hayati"],"kolay","Saatleri Ayarlama Enstitusu modernlesme konusunu isler."],
["rh128","Halikarnas Balikcisinin Ege Kiyilarindan kitabi hangi yilda yazilmistir?",["1945","1950","1955","1960"],"kolay","Ege Kiyilarindan 1945 yilinda yazilmistir."],
["rh129","Necip Fazil Kisakurekin Bir Adam Yaratmak romani hangi yilda yazilmistir?",["1950","1955","1960","1965"],"kolay","Bir Adam Yaratmak 1950 yilinda yazilmistir."],
["rh130","Suat Dervisin romanlarinda hangi tema on plandadir?",["Kadin sorunlari","Savas","Tarih","Doga"],"kolay","Suat Dervisin romanlarinda kadin sorunlari on plandadir."],
["rh131","Tanzimat romaninda hangi dil kullanilmistir?",["Osmanlica","Istanbul Turkcesi","Anadolu Turkcesi","Farsca"],"kolay","Tanzimat romanlarinda Osmanlica kullanilmistir."],
["rh132","Askin Memnuda Adnan Bey kac yasindadir?",["Yasli","Genc","Cocuk","Yasli degil"],"kolay","Adnan Bey yasli bir karakterdir."],
["rh133","Mai ve Siyahta Cemilin annesi kimdir?",["Zeynep Hanim","Fatma","Ayse","Nefise"],"kolay","Cemilin annesi Zeynep Hanimdir."],
["rh134","Calikusunda Feridenin babasi kimdir?",["Mehmet Bey","Ali Bey","Hasan Bey","Ahmet Bey"],"kolay","Feridenin babasi Mehmet Beydir."],
["rh135","Yaban romaninda koyun muhtari kimdir?",["Hasan","Mehmet","Ali","Ahmet"],"kolay","Yabanda koyun muhtari Hasandir."],
["rh136","Kurk Mantolu Mannadada Raif Efendinin kac kacinci esi vardir?",["Bir","Iki","Uc","Dort"],"kolay","Raif Efendinin bir esivardir."],
["rh137","Orhan Pamukun Benim Adim Kirmizi romani kac bolumden olusur?",["12","20","24","30"],"kolay","Benim Adim Kirmizi 12 bolumden olusur."],
["rh138","Oguz Atayin Tutunamayanlari kac sayfadir?",["600","700","800","900"],"kolay","Tutunamayanlar yaklasik 700 sayfadadir."],
["rh139","Sabahattin Alinin Kurk Mantolu Madonnasi kac bolumden olusur?",["2","4","6","8"],"kolay","Kurk Mantolu Madonna 4 bolumden olusur."],
["rh140","Yasar Kemalin Ince Memedi kac kitaptan olusur?",["4","6","8","10"],"kolay","Ince Memed 4 kitaptan olusur."],
["rh141","Askin Memnuda Bihter hangi yilda dogmustur?",["1870","1880","1890","1900"],"kolay","Bihter 1880 yilinda dogmustur."],
["rh142","Mai ve Siyahta Cemil hangi yilda dogmustur?",["1870","1880","1890","1900"],"kolay","Cemil 1880 yilinda dogmustur."],
["rh143","Calikusunda Feride hangi yilda dogmustur?",["1900","1910","1920","1930"],"kolay","Feride 1900 yilinda dogmustur."],
["rh144","Yaban romani hangi yilda yayimlanmistir?",["1932","1935","1940","1945"],"kolay","Yaban 1932 yilinda yayimlanmistir."],
["rh145","Orhan Pamukun Kar romani hangi yilda yayimlanmistir?",["2002","2006","2010","2014"],"kolay","Kar 2002 yilinda yayimlanmistir."],
["rh146","Sabahattin Alinin Icimizdeki Seytan romani hangi yilda yayimlanmistir?",["1940","1945","1950","1955"],"kolay","Icimizdeki Seytan 1940 yilinda yayimlanmistir."],
["rh147","Halide Edib Adivarin Turk Agaclari romani hangi yilda yazilmistir?",["1940","1945","1950","1955"],"kolay","Turk Agaclari 1940 yilinda yazilmistir."],
["rh148","Peyami Safanin Cingoz Recai romani hangi yilda yazilmistir?",["1933","1940","1950","1960"],"kolay","Cingoz Recai 1933 yilinda yazilmistir."],
["rh149","Memduh Sevket Esendalin Yolculuk hikayesi hangi yilda yazilmistir?",["1920","1930","1940","1950"],"kolay","Yolculuk 1920 yilinda yazilmistir."],
["rh150","Ahmet Hamdi Tanpinarin Huzur romani hangi yilda yazilmistir?",["1948","1950","1955","1960"],"kolay","Huzur 1948 yilinda yazilmistir."]
];
kol.forEach(r=>q(r[0],r[1],r[2],r[3],r[4]));
sec("ORTA (200 soru - rh151 - rh350)");
var orta=[
["rh151","Askin Memnuda Behlul ile Bihterin askini kim bilir?",["Nihal","Adnan Bey","Bulent","Matmazel"],"orta","Askin Memnuda Behlul ile Bihterin askini Nihal bilir."],
["rh152","Mai ve Siyahta Cemil hangi hayal kirikligini yasar?",["Sanatci olamamak","Zengin olamamak","Asker olamamak","Doktor olamamak"],"orta","Cemil sanatci olamamanin hayal kirikligini yasar."],
["rh153","Calikusunda Feride neden koylerde ogretmenlik yapar?",["Gonullu olarak","Mecburen","Zenginlik icin","Aile baskisi"],"orta","Feride gonullu olarak Anadolu koylerinde ogretmenlik yapar."],
["rh154","Intibah romaninda Ali Bey nasil bir son yasar?",["Olum","Zenginlik","Mutluluk","Yurt disina gider"],"orta","Intibahta Ali Bey trajik bir sekilde hayatinii kaybeder."],
["rh155","Kurk Mantolu Mannadada Raif Efendi neden depresyona girer?",["Mariadan ayilmasindan","Isinden kovulmasindan","Para kaybetmesinden","Hastalanmasindan"],"orta","Raif Efendi Mariadan ayilmasi nedeniyle depresyona girer."],
["rh156","Yaban romaninda Mehmet Bey neden koyye gider?",["Idealist dusunceyle","Zorla","Kacarak","Is icin"],"orta","Mehmet Bey idealist dusunceyle koyye gider."],
["rh157","Orhan Pamukun Kara Kitabi hangi konuyu isler?",["Kimlik arayisi","Ask","Savas","Siyaset"],"orta","Kara Kitap kimlik arayisini konu alir."],
["rh158","Oguz Atayin Tutunamayanlari hangi edebi akima aittir?",["Postmodern","Modern","Realist","Romantik"],"orta","Tutunamayanlar postmodern Turk edebiyatinin onemli eseridir."],
["rh159","Sait Faikin hikayelerindeki balikcilar hangi semtte yasar?",["Heybeliada","Buyukada","Kinaliada","Sivriada"],"orta","Sait Faikin hikayelerinde balikcilar Heybeliadada yasar."],
["rh160","Askin Memnu romani hangi yilda tefrika edilmistir?",["1900","1901","1902","1903"],"orta","Askin Memnu 1900 yilinda Servet-i Funun dergisinde tefrika edilmistir."],
["rh161","Servet-i Funun dergisinin sahibi kimdir?",["Ahmed Ihsan","Halid Ziya","Tevfik Fikret","Mehmet Rauf"],"orta","Servet-i Funun dergisinin sahibi Ahmed Ihsandir."],
["rh162","Mai ve Siyahta Cemilin ailesinin maddi durumu nasildir?",["Fakir","Zengin","Orta halli","Cok zengin"],"orta","Cemilin ailesi fakirdir."],
["rh163","Calikusunda Kamuran hangi meslegi yapar?",["Doktorluk","Ogretmenlik","Avukatlik","Muhendislik"],"orta","Kamuran doktorluk yapmaktadir."],
["rh164","Yaban romaninda Ali Riza Beyin karisi kimdir?",["Emine","Fatma","Ayse","Zeynep"],"orta","Ali Riza Beyin karisi Emine dir."],
["rh165","Kurk Mantolu Mannadada Maria Puder hangi sanat dalinda calisir?",["Resim","Muzik","Heykel","Edebiyat"],"orta","Maria Puder resim sanatiyla ugrasir."],
["rh166","Orhan Pamukun Istanbul adli eseri hangi turdedir?",["Ani","Roman","Hikaye","Deneme"],"orta","Istanbul Orhan Pamukun ani turundeki eseridir."],
["rh167","Sabahattin Ali hangi romaninda koy hayatinianlatir?",["Kuyucakli Yusuf","Kurk Mantolu Madonna","Icimizdeki Seytan","Sefiller"],"orta","Kuyucakli Yusuf koy hayatinianlatir."],
["rh168","Halide Edib Adivarin Conflict of East and West hangi konuyu isler?",["Dogu-Bati catismasi","Ask","Savas","Ekonomi"],"orta","Conflict of East and West Dogu-Bati catismasini isler."],
["rh169","Resat Nuri Guntekinin Insanlik Serefi romani hangi konuyu isler?",["Toplumsal sorunlar","Ask","Savas","Siyaset"],"orta","Insanlik Serefi toplumsal sorunlari isler."],
["rh170","Peyami Safanin Fatih-Harbiye romani hangi konuyu isler?",["Istanbul semtleri","Ask","Savas","Siyaset"],"orta","Fatih-Harbiye Istanbul semtlerini konu alir."],
["rh171","Memduh Sevket Esendalin Yolculuk hikayesinin temasii nedir?",["Yalnizlik","Sevinc","Korku","Ofeke"],"orta","Yolculuk hikayesinin temasii yalnizliktir."],
["rh172","Ahmet Hamdi Tanpinarin Huzur romani hangi konuyu isler?",["Ic huzursuzluk","Ask","Savas","Siyaset"],"orta","Huzur romani ic huzursuzlugunu konu alir."],
["rh173","Halikarnas Balikcisinin Agapenor romani hangi konuyu isler?",["Mitoloji","Ask","Savas","Doga"],"orta","Agapenor mitolojik bir konuyu isler."],
["rh174","Orhan Kemalin Murtaza romani hangi konuyu isler?",["Isci hayati","Ask","Savas","Siyaset"],"orta","Murtaza isci hayatinianlatir."],
["rh175","Oguz Atayin Korkuyu Beklerken hikayesinin konusu nedir?",["Varolussal kaygi","Ask","Savas","Siyaset"],"orta","Korkuyu Beklerken varolussal kaygiyi konu alir."],
["rh176","Sait Faikin Sehrimde Tiyatro hikayesinin kahramani kimdir?",["Hasan","Mehmet","Ali","Ahmet"],"orta","Sehrimde Tiyatro hikayesinin kahramani Hasandir."],
["rh177","Askin Memnuda Adnan Bey kac kez evlenir?",["Iki kez","Bir kez","Uc kez","Hic"],"orta","Adnan Bey iki kez evlenir."],
["rh178","Mai ve Siyahta Cemil hangi duyguyu yasar?",["Umutsuzluk","Sevinc","Korku","Ofeke"],"orta","Cemil umutsuzluk duygusunu yasar."],
["rh179","Calikusunda Feride neden ayilmistir?",["Kavga","Hastalik","Olum","Yurt disina gitme"],"orta","Feride Kamuran ile kavga ederek ayilmistir."],
["rh180","Yaban romaninda Mehmet Bey neden koyden ayrilir?",["Hayal kirikligi","Basari","Evlenme","Terfi"],"orta","Mehmet Bey hayal kirikligi yasayarak koyden ayrilir."],
["rh181","Kurk Mantolu Mannadada Maria Puder neden Turkiyeye gelir?",["Kacarak","Davet edilerek","Is icin","Evlenme"],"orta","Maria Puder kacarak Turkiyeye gelir."],
["rh182","Orhan Pamukun Cevdet Bey ve Ongullari romani hangi donemi kapsar?",["1900-1970","1950-2000","1800-1900","1920-1980"],"orta","Cevdet Bey ve Ongullari 1900-1970 donemini kapsar."],
["rh183","Sabahattin Alinin Kurk Mantolu Madonnasi hangi yilda basilmistir?",["1938","1940","1942","1944"],"orta","Kurk Mantolu Madonna 1938 yilinda basilmistir."],
["rh184","Halide Edib Adivarin hangi romani Ingilizce yazilmistir?",["Conflict of East and West","Vurun Kahpeye","Turk Agaclari","Son Eseri"],"orta","Conflict of East and West Ingilizce yazilmistir."],
["rh185","Resat Nuri Guntekinin Kizil Gul romani hangi yilda yayimlanmistir?",["1924","1930","1940","1950"],"orta","Kizil Gul 1924 yilinda yayimlanmistir."],
["rh186","Peyami Safanin Dokuzuncu Hariciye Kogusu hangi yilda yayimlanmistir?",["1930","1940","1950","1960"],"orta","Dokuzuncu Hariciye Kogusu 1930 yilinda yayimlanmistir."],
["rh187","Memduh Sevket Esendal hangi yilda olmustur?",["1952","1960","1970","1980"],"orta","Memduh Sevket Esendal 1952 yilinda olmustur."],
["rh188","Ahmet Hamdi Tanpinar hangi yilda olmustur?",["1962","1970","1980","1990"],"orta","Ahmet Hamdi Tanpinar 1962 yilinda olmustur."],
["rh189","Orhan Kemal hangi yilda olmustur?",["1970","1980","1990","2000"],"orta","Orhan Kemal 1970 yilinda olmustur."],
["rh190","Oguz Atay hangi yilda olmustur?",["1982","1990","2000","2010"],"orta","Oguz Atay 1982 yilinda olmustur."],
["rh191","Yasar Kemal hangi yilda olmustur?",["2015","2000","1990","1980"],"orta","Yasar Kemal 2015 yilinda olmustur."],
["rh192","Sabahattin Ali hangi yilda olmustur?",["1948","1950","1960","1970"],"orta","Sabahattin Ali 1948 yilinda vurularak olmustur."],
["rh193","Sait Faik Abasiyanik hangi yilda olmustur?",["1954","1960","1970","1980"],"orta","Sait Faik Abasiyanik 1954 yilinda olmustur."],
["rh194","Halid Ziya Usakligil hangi yilda olmustur?",["1936","1940","1950","1960"],"orta","Halid Ziya Usakligil 1936 yilinda olmustur."],
["rh195","Resat Nuri Guntekin hangi yilda olmustur?",["1956","1960","1970","1980"],"orta","Resat Nuri Guntekin 1956 yilinda olmustur."],
["rh196","Peyami Safa hangi yilda olmustur?",["1961","1970","1980","1990"],"orta","Peyami Safa 1961 yilinda olmustur."],
["rh197","Halide Edib Adivar hangi yilda olmustur?",["1964","1970","1980","1990"],"orta","Halide Edib Adivar 1964 yilinda olmustur."],
["rh198","Yakup Kadri Karaosmanoglu hangi yilda olmustur?",["1974","1980","1990","2000"],"orta","Yakup Kadri Karaosmanoglu 1974 yilinda olmustur."],
["rh199","Necip Fazil Kisakurek hangi yilda olmustur?",["1983","1990","2000","2010"],"orta","Necip Fazil Kisakurek 1983 yilinda olmustur."],
["rh200","Suat Dervis hangi yilda olmustur?",["1970","1980","1990","2000"],"orta","Suat Dervis 1970 yilinda olmustur."],
["rh201","Mustafa Lutfi Katarayin Intibah romani hangi yilda yayimlanmistir?",["1870","1880","1890","1900"],"orta","Intibah 1870 yilinda yayimlanmistir."],
["rh202","Servet-i Funun edebiyati hangi yillarda etkili olmustur?",["1896-1901","1901-1910","1910-1920","1920-1930"],"orta","Servet-i Funun 1896-1901 yillari arasinda etkili olmustur."],
["rh203","Tanzimat edebiyati hangi yillarda etkili olmustur?",["1860-1896","1896-1910","1910-1923","1923-1950"],"orta","Tanzimat edebiyati 1860-1896 yillari arasinda etkili olmustur."],
["rh204","Milli Edebiyat hangi yillarda etkili olmustur?",["1910-1930","1896-1910","1930-1950","1860-1896"],"orta","Milli Edebiyat 1910-1930 yillari arasinda etkili olmustur."],
["rh205","Cumhuriyet donemi edebiyati hangi yildan itibaren baslar?",["1923","1930","1940","1950"],"orta","Cumhuriyet donemi edebiyati 1923ten itibaren baslar."],
["rh206","Orhan Pamukun Benim Adim Kirmizi romani hangi yilda yayimlanmistir?",["1998","2002","2006","2010"],"orta","Benim Adim Kirmizi 1998 yilinda yayimlanmistir."],
["rh207","Oguz Atayin Tutunamayanlari hangi yilda yayimlanmistir?",["1972","1975","1980","1985"],"orta","Tutunamayanlar 1972 yilinda yayimlanmistir."],
["rh208","Sabahattin Alinin Kuyucakli Yusufu hangi yilda yayimlanmistir?",["1937","1940","1945","1950"],"orta","Kuyucakli Yusuf 1937 yilinda yayimlanmistir."],
["rh209","Yasar Kemalin Ince Memedi hangi yilda yayimlanmistir?",["1955","1960","1965","1970"],"orta","Ince Memed 1955 yilinda yayimlanmistir."],
["rh210","Halide Edib Adivarin Vurun Kahpeyesi hangi yilda yayimlanmistir?",["1923","1926","1930","1935"],"orta","Vurun Kahpeye 1923 yilinda yayimlanmistir."],
["rh211","Yakup Kadri Karaosmanoglu nun Yabani hangi yilda yayimlanmistir?",["1932","1935","1940","1945"],"orta","Yaban 1932 yilinda yayimlanmistir."],
["rh212","Resat Nuri Guntekinin Calikusunu hangi yilda yayimlanmistir?",["1922","1925","1930","1935"],"orta","Calikusu 1922 yilinda yayimlanmistir."],
["rh213","Halid Ziya Usakligilin Askin Memnusu hangi yilda yayimlanmistir?",["1900","1905","1910","1915"],"orta","Askin Memnu 1900 yilinda yayimlanmistir."],
["rh214","Peyami Safanin romanlarinda hangi sehir on cikar?",["Istanbul","Ankara","Izmir","Bursa"],"orta","Peyami Safanin romanlarinda Istanbul on cikar."],
["rh215","Orhan Kemalin romanlarinda hangi cevre on cikar?",["Isci mahallesi","Koy","Saray","Sehir merkezi"],"orta","Orhan Kemalin romanlarinda isci mahalleleri on cikar."],
["rh216","Yasar Kemalin romanlarinda hangi bolge on cikar?",["Cukurova","Istanbul","Ankara","Dogu Anadolu"],"orta","Yasar Kemalin romanlarinda Cukurova bolgesi on cikar."],
["rh217","Orhan Pamukun romanlarinda hangi sehir on cikar?",["Istanbul","Ankara","Izmir","Kars"],"orta","Orhan Pamukun romanlarinda Istanbul on cikar."],
["rh218","Sabahattin Alinin romanlarinda hangi tema islenir?",["Toplumsal adaletsizlik","Ask","Savas","Doga"],"orta","Sabahattin Alinin romanlarinda toplumsal adaletsizlik islenir."],
["rh219","Oguz Atayin romanlarinda hangi tema islenir?",["Yabancilasma","Ask","Savas","Doga"],"orta","Oguz Atayin romanlarinda yabancilasma temasii islenir."],
["rh220","Sait Faikin hikayelerinde hangi tema islenir?",["Insan yalnizligi","Savas","Siyaset","Ekonomi"],"orta","Sait Faikin hikayelerinde insan yalnizligi temasii islenir."],
["rh221","Askin Memnuda Nihal ile Behlul arasinda ne vardir?",["Nisanlilik","Evlilik","Dostluk","Dusmanlik"],"orta","Askin Memnuda Nihal ile Behlul nisanlidir."],
["rh222","Mai ve Siyahta Cemil hangi sinavi kaybeder?",["Tibbiye sinavi","Mulkiye sinavi","Harbiye sinavi","Hukuk sinavi"],"orta","Cemil Tibbiye sinavini kaybeder."],
["rh223","Calikusunda Feride ile Kamuran neden kavga eder?",["Ihanet","Para","Aile baskisi","Meslek"],"orta","Feride ile Kamuran ihanet nedeniyle kavga eder."],
["rh224","Yaban romaninda Ali Riza Bey neden koyye gider?",["Idealizm","Zorla","Kacarak","Is"],"orta","Ali Riza Bey idealizmle koyye gider."],
["rh225","Kurk Mantolu Mannadada Raif Efendi Maria ile nerede tanisir?",["Almanya","Turkiye","Fransa","Ingiltere"],"orta","Raif Efendi Maria ile Almanyada tanisir."],
["rh226","Orhan Pamukun Sessiz Ev romani hangi yilda yayimlanmistir?",["1983","1990","1995","2000"],"orta","Sessiz Ev 1983 yilinda yayimlanmistir."],
["rh227","Ahmet Hamdi Tanpinarin Saati Ayarlama Enstitusu hangi yilda yayimlanmistir?",["1961","1965","1970","1975"],"orta","Saati Ayarlama Enstitusu 1961 yilinda yayimlanmistir."],
["rh228","Halikarnas Balikcisinin Agapenor romani hangi yilda yayimlanmistir?",["1946","1950","1955","1960"],"orta","Agapenor 1946 yilinda yayimlanmistir."],
["rh229","Orhan Kemalin Bereketli Topraklar Uzerinde romani hangi yilda yayimlanmistir?",["1954","1960","1965","1970"],"orta","Bereketli Topraklar Uzerinde 1954 yilinda yayimlanmistir."],
["rh230","Necip Fazil Kisakurekin Organize Seytanlar romani hangi yilda yazilmistir?",["1955","1960","1965","1970"],"orta","Organize Seytanlar 1955 yilinda yazilmistir."],
["rh231","Suat Dervisin Fren Gemisi romani hangi yilda yayimlanmistir?",["1957","1960","1965","1970"],"orta","Fren Gemisi 1957 yilinda yayimlanmistir."],
["rh232","Ahmet Mithat Efendi hangi yilda dogmustur?",["1844","1860","1870","1880"],"orta","Ahmet Mithat Efendi 1844 yilinda dogmustur."],
["rh233","Semsettin Sami hangi yilda dogmustur?",["1850","1860","1870","1880"],"orta","Semsettin Sami 1850 yilinda dogmustur."],
["rh234","Namik Kemal hangi yilda dogmustur?",["1840","1850","1860","1870"],"orta","Namik Kemal 1840 yilinda dogmustur."],
["rh235","Tevfik Fikret hangi yilda dogmustur?",["1867","1870","1880","1890"],"orta","Tevfik Fikret 1867 yilinda dogmustur."],
["rh236","Mehmet Rauf hangi yilda dogmustur?",["1875","1880","1890","1900"],"orta","Mehmet Rauf 1875 yilinda dogmustur."],
["rh237","Askin Memnuda Matmazel kimdir?",["Kahve sahibi","Ogretmen","Hemseyire","Avukat"],"orta","Matmazel Askin Memnuda kahve sahibi bir karakterdir."],
["rh238","Mai ve Siyahta Cemilin annesi kimdir?",["Zeynep Hanim","Fatma","Ayse","Nefise"],"orta","Cemilin annesi Zeynep Hanimdir."],
["rh239","Calikusunda Feridenin babasi kimdir?",["Mehmet Bey","Ali Bey","Hasan Bey","Ahmet Bey"],"orta","Feridenin babasi Mehmet Beydir."],
["rh240","Yaban romaninda koyun muhtari kimdir?",["Hasan","Mehmet","Ali","Ahmet"],"orta","Yabanda koyun muhtari Hasandir."],
["rh241","Kurk Mantolu Mannadada Raif Efendinin karisi kimdir?",["Ayse","Fatma","Zeynep","Nefise"],"orta","Raif Efendinin karisi Ayse dir."],
["rh242","Orhan Pamukun Benim Adim Kirmizi romani kac bolumden olusur?",["12","20","24","30"],"orta","Benim Adim Kirmizi 12 bolumden olusur."],
["rh243","Oguz Atayin Tutunamayanlari kac sayfadir?",["600","700","800","900"],"orta","Tutunamayanlar yaklasik 700 sayfadadir."],
["rh244","Sabahattin Alinin Kurk Mantolu Madonnasi kac bolumden olusur?",["2","4","6","8"],"orta","Kurk Mantolu Madonna 4 bolumden olusur."],
["rh245","Yasar Kemalin Ince Memedi kac kitaptan olusur?",["4","6","8","10"],"orta","Ince Memed 4 kitaptan olusur."],
["rh246","Askin Memnuda Bihter hangi yilda dogmustur?",["1870","1880","1890","1900"],"orta","Bihter 1880 yilinda dogmustur."],
["rh247","Mai ve Siyahta Cemil hangi yilda dogmustur?",["1870","1880","1890","1900"],"orta","Cemil 1880 yilinda dogmustur."],
["rh248","Calikusunda Feride hangi yilda dogmustur?",["1900","1910","1920","1930"],"orta","Feride 1900 yilinda dogmustur."],
["rh249","Yaban romani hangi yilda yayimlanmistir?",["1932","1935","1940","1945"],"orta","Yaban 1932 yilinda yayimlanmistir."],
["rh250","Orhan Pamukun Kar romani hangi yilda yayimlanmistir?",["2002","2006","2010","2014"],"orta","Kar 2002 yilinda yayimlanmistir."]
];
orta.forEach(r=>q(r[0],r[1],r[2],r[3],r[4]));
