const fs = require('fs');
const path = 'C:\\Users\\User\\AppData\\Local\\Temp\\osmanli-edebiyat\\src\\data\\kategoriler\\dunya-edebiyati.ts';

const q = (id, s, o, d, z, b) => `  { id: '${id}', soru: '${s.replace(/'/g, "\\'")}', secenekler: [${o.map(x=>`'${x.replace(/'/g,"\\'")}'`).join(',')}], dogruCevap: ${d}, kategori: 'Dünya Edebiyatı', zorluk: '${z}', bilgi: '${b.replace(/'/g,"\\'")}' },`;

const L = [];
L.push("import { Soru } from '../../types';");
L.push("export const dunyaEdebiyatiSorulari: Soru[] = [");
L.push("");

// ===== 50 cokKolay =====
L.push("  // 50 cokKolay");
const ck = [
['de001', 'İlyada ve Odysseia destanlarının yazarı kimdir?', ['Homeros','Virgilius','Ovidius','Horatius'], 0, 'Homeros, Antik Yunan edebiyatının en büyük destan yazarıdır.'],
['de002', 'Shakespeare\'in "Hamlet" oyununda "Olmak ya da olmamak" repliği geçer. Hamlet hangi ülkede geçer?', ['İtalya','İngiltere','Danimarka','Fransa'], 2, 'Hamlet, Danimarka prensidir.'],
['de003', 'Dante Alighieri\'nin İlahi Komedya\'sı hangi dille yazılmıştır?', ['Latince','İtalyanca','Fransızca','İspanyolca'], 1, 'Dante, İlahi Komedya\'yı İtalyanca yazmıştır.'],
['de004', 'Don Kişot romanının yazarı kimdir?', ['Cervantes','Calderón','Lope de Vega','Garcilaso'], 0, 'Miguel de Cervantes, İspanyol edebiyatının en büyük yazarlarındandır.'],
['de005', 'George Orwell\'in "1984" romanında baskının simgesi olan liderin adı nedir?', ['Büyük Birader','Big Brother','Parti','Yurtseverlik'], 0, 'Büyük Birader, 1984 romanında rejimin simgesidir.'],
['de006', 'William Shakespeare hangi ülkede yaşamıştır?', ['İtalya','Fransa','İngiltere','Almanya'], 2, 'Shakespeare, İngiltere\'nin StratfordUponAvon kasabasında doğmuştur.'],
['de007', 'Antik Yunan tragedyasının üç büyük yazarı Sophokles, Euripides ve kimdir?', ['Aristophanes','Aiskhylos','Platon','Aristoteles'], 1, 'Aiskhylos, Sophokles ve Euripides üç büyük tragedyacıdır.'],
['de008', 'Hemingway\'in "İhtiyar Adam ve Deniz" romanı hangi yıl Pulitzer Ödülü kazanmıştır?', ['1950','1952','1954','1956'], 1, 'İhtiyar Adam ve Deniz, 1952\'de Pulitzer Ödülü kazanmıştır.'],
['de009', 'Gabriel García Márquez hangi ülkeli bir yazardır?', ['Meksika','Arjantin','Kolombiya','Şili'], 2, 'García Márquez, Kolombiyalı yazar ve Nobel ödüllüdür.'],
['de010', 'Tolstoy\'un "Savaş ve Barış" romanı hangi savaşta geçmektedir?', ['Kırım Savaşı','Napolyon Savaşları','Rus-Japon Savaşı','Birinci Dünya Savaşı'], 1, 'Savaş ve Barış, Napolyon\'un Rusya seferini anlatır.'],
['de011', 'Dostoyevski\'nin "Suç ve Ceza" romanında başkahramanın adı nedir?', ['Raskolnikov','Karamazov','Myshkin','Golyadkin'], 0, 'Raskolnikov, Suç ve Ceza\'nın başkahramanıdır.'],
['de012', 'Kafka\'nın "Dönüşüm" romanında Gregor Samsa neye dönüşür?', ['Böcek','Kurbağa','Köpek','Kuş'], 0, 'Gregor Samsa, bir böceğe dönüşür.'],
['de013', 'Shakespeare\'in "Romeo ve Juliet" eseri hangi şehirde geçer?', ['Venedik','Verona','Roma','Milano'], 1, 'Romeo ve Juliet, İtalya\'nın Verona şehrinde geçmektedir.'],
['de014', 'Homeros\'un Odysseia destanında kahramanın adı nedir?', ['Akhilleus','Odysseus','Hektor','Agamemnon'], 1, 'Odysseus, Odysseia destanının kahramanıdır.'],
['de015', 'Orwell\'in "Hayvan Çiftliği" romanında domuzların lideri kimdir?', ['Napolyon','Şöhret','Büyük Birader','Squealer'], 0, 'Napolyon, Hayvan Çiftliği\'ndeki domuz lideridir.'],
['de016', 'Cervantes\'in Don Kişot\'unda şövalyenin sadık uşağının adı nedir?', ['Sancho Panza','Rocinante','Dulcinea','Cardenio'], 0, 'Sancho Panza, Don Kişot\'un sadık uşağıdır.'],
['de017', 'Dante\'nin İlahi Komedya\'sında cehennemin girişindeki levhada ne yazar?', ['Giriş yasaktır','Biranızı terk edin','Buradan geri dönüş yok','Dikkatli olun'], 2, 'Kapıda "Buranızdan umudunuzu terk edin" yazar.'],
['de018', 'Tolstoy\'un "Anna Karenina" romanı hangi yüzyılda geçmektedir?', ['17. yüzyıl','18. yüzyıl','19. yüzyıl','20. yüzyıl'], 2, 'Anna Karenina, 19. yüzyıl Rusyası\'nda geçmektedir.'],
['de019', 'Hemingway\'in "Çanlar Kimin İçin Çalıyor" romanı hangi savaşta geçer?', ['İspanya İç Savaşı','İkinci Dünya Savaşı','Kore Savaşı','Vietnam Savaşı'], 0, 'Roman, İspanya İç Savaşı sırasında geçmektedir.'],
['de020', 'Sophokles\'in "Oedipus" tragedyasında Oedipus\'un karısı ve annesi aynı kişidir. Bu kişi kimdir?', ['Klytemnestra','Jokasta','Antigone','Electra'], 1, 'Jokasta, Oedipus\'un hem annesi hem karısıdır.'],
['de021', 'Gabriel García Márquez\'in "Yüzyıllık Yalnızlık" romanı hangi ülkede geçer?', ['Meksika','Kolombiya','Arjantin','Peru'], 1, 'Roman, Kolombiya\'da Macondo adlı kurgusal bir kasabada geçer.'],
['de022', 'Shakespeare\'in "Macbeth" oyununda Macbeth hangi unvanı taşır?', ['Dük','Kral','Prens','Baron'], 1, 'Macbeth, İskoçya kralı olmuştur.'],
['de023', 'Dostoyevski\'nin "Budala" romanında Prens Myshkin hangi hastalığa sahiptir?', ['Epilepsi','Şizofreni','Kan kanseri','Verem'], 0, 'Prens Myshkin epilepsi hastasıdır.'],
['de024', 'Kafka\'nın "Dava" romanında Josef K. neyle suçlanır?', ['Hırsızlık','Cinayet','Suçu belirsiz','Vergi kaçırma'], 2, 'Josef K.\'nın suçu roman boyunca açıklanmaz.'],
['de025', 'Troya Savaşı\'nda en güçlü savaşçı olarak bilinen kahraman kimdir?', ['Odysseus','Akhilleus','Hektor','Ajax'], 1, 'Akhilleus, Troya Savaşı\'nın en güçlü savaşçısıdır.'],
['de026', 'Orwell\'in "1984" romanında düşünceleri izleyen polis teşkilatı hangisidir?', ['Düşünce polisliği','Sınır güvenliği','Trafik polisliği','Mali polislik'], 0, 'Thought Police, düşünceleri izleyen polis teşkilatıdır.'],
['de027', 'Tolstoy kimdir?', ['Fransız romancı','Rus romancı','Alman romancı','İngiliz romancı'], 1, 'Lev Tolstoy, Rus edebiyatının en büyük yazarlarındandır.'],
['de028', 'Sophokles\'in "Antigone" tragedyasında Antigone neden cezalandırılır?', ['Hırsızlık','Kardeşini gömmesi','Krala karşı gelmesi','Yalan söylemesi'], 1, 'Antigone, yasak olmasına rağmen kardeşini gömer.'],
['de029', 'Shakespeare\'in "Othello" oyununda Othello hangi ırktan bir karakterdir?', ['Beyaz','Siyahi','Asyalı','Kızılderili'], 1, 'Othello, siyahi bir Venedikli generdir.'],
['de030', 'Dante\'nin İlahi Komedya\'sında cennetin en üst katında kim vardır?', ['Meryem','Tanrı','Aziz Petrus','Adem'], 1, 'Cennetin en üst katında Tanrı vardır.'],
['de031', 'Hemingway hangi edebi akımla ilişkilendirilir?', ['Romantizm','Minimalizm','Sürrealizm','Ekspresyonizm'], 1, 'Hemingway, minimalizm ve "buzdağı teorisi" ile tanınır.'],
['de032', 'Cervantes\'in Don Kişot\'u hangi yüzyılda yazılmıştır?', ['15. yüzyıl','16. yüzyıl','17. yüzyıl','18. yüzyıl'], 1, 'Don Kişot, 1605 ve 1615\'te yayımlanmıştır.'],
['de033', 'Gabriel García Márquez hangi edebi akımın öncülerinden biridir?', ['Gerçeküstücülük','Büyüsel gerçekçilik','Modernizm','Postmodernizm'], 1, 'García Márquez, büyüsel gerçekçilik akımının en önemli temsilcisidir.'],
['de034', 'Dostoyevski hangi ülkede yaşamıştır?', ['Polonya','Rusya','Ukrayna','Çek Cumhuriyeti'], 1, 'Dostoyevski, Rus edebiyatının en büyük yazarlarındandır.'],
['de035', 'Shakespeare\'in "Kral Lear" oyununda kaç kızı vardır?', ['İki','Üç','Dört','Beş'], 1, 'Kral Lear\'ın üç kızı vardır.'],
['de036', 'Homeros\'un İlyada destanı hangi savaşı anlatır?', ['Pers Savaşları','Troya Savaşı','Peloponez Savaşı','Makedon Savaşları'], 1, 'İlyada, Troya Savaşı\'nı anlatır.'],
['de037', 'Kafka hangi ülkede yaşamıştır?', ['Almanya','Avusturya','Çek Cumhuriyeti','Macaristan'], 2, 'Kafka, Prag\'da doğmuştur.'],
['de038', 'Tolstoy\'un "Kazaklar" romanında başkahraman hangi unvandadır?', ['Asker','Subay','Memur','Öğretmen'], 1, 'Kazaklar\'ın başkahramanı bir subaydır.'],
['de039', 'Hemingway hangi yıl Nobel Edebiyat Ödülü\'nü kazanmıştır?', ['1952','1954','1956','1958'], 1, 'Hemingway, 1954\'te Nobel Edebiyat Ödülü\'nü kazanmıştır.'],
['de040', 'Sophokles\'in "Elektra" tragedyasında Elektra kimin intikamını almak ister?', ['Babasının','Erkek kardeşinin','Kocasının','Annesinin'], 0, 'Elektra, babası Agamemnon\'un intikamını almak ister.'],
['de041', 'Shakespeare\'in "Soner Perisi" oyununda Puck hangi varlıktır?', ['İnsan','Peri','Cin','Melek'], 1, 'Puck, Soner Perisi\'ndeki mizahi peri karakteridir.'],
['de042', 'Dante\'nin İlahi Komedya\'sında Virgilius Dante\'ye ne yapar?', ['Cennete götürür','Cehennem ve arafı gösterir','Öğretmenlik yapar','Savaşır'], 1, 'Virgilius, Dante\'ye cehennem ve arafı gösterir.'],
['de043', 'Cervantes\'in Don Kişot\'unda Dulcinea kimsidir?', ['Bir prenses','Bir köylü kızı','Bir kraliçe','Bir rahibe'], 1, 'Dulcinea, Don Kişot\'un hayalindeki sevgilidir.'],
['de044', 'Orwell\'in "1984" romanında "Newspeak" nedir?', ['Yeni dil','Yeni din','Yeni hükümet','Yeni şehir'], 0, 'Newspeak, devletin dayattığı yeni dildir.'],
['de045', 'Tolstoy\'un "Kazaklar" romanı hangi savaşı konu alır?', ['Kırım Savaşı','Napolyon Savaşları','Rus-Türk Savaşı','Birinci Dünya Savaşı'], 0, 'Kazaklar, Kırım Savaşı sırasında geçmektedir.'],
['de046', 'Dostoyevski\'nin "İdiot" romanında Prens Myshkin hangi ülkeden döner?', ['İtalya','İsviçre','Fransa','Almanya'], 1, 'Prens Myshkin, İsviçre\'den döner.'],
['de047', 'Kafka\'nın "Dava" romanında Josef K. hangi mesleği yapar?', ['Avukat','Bankacı','Mimar','Doktor'], 1, 'Josef K., bir banka memurudur.'],
['de048', 'Hemingway\'in "Güneş de Doğar" romanı hangi ülkede geçer?', ['Fransa','İspanya','İtalya','İngiltere'], 1, 'Roman, İspanya\'nın Pamplona şehrinde geçer.'],
['de049', 'Sophokles\'in "Oedipus" tragedyasında Oedipus\'un babası kimdir?', ['Laios','Kreon','Theseus','Perikles'], 0, 'Laios, Oedipus\'un gerçek babasıdır.'],
['de050', 'Shakespeare\'in "Venedik Tüccarı" oyununda Antonio kimin borcunu ödemek için çabalar?', ['Portia','Bassanio','Gratiano','Lorenzo'], 1, 'Antonio, Bassanio için Shylock\'tan borç alır.'],
];
ck.forEach(d => L.push(q(d[0],d[1],d[2],d[3],'cokKolay',d[4])));

// ===== 100 kolay =====
L.push("");
L.push("  // 100 kolay");
const ky = [
['de051', 'Homeros\'un İlyada\'sında Akhilleus\'un öfkesi neyle başlar?', ['Kız kardeşi','Sevgilisi','Esir için çekişme','Kalkanı'], 2, 'Akhilleus, Briseis için Agamemnon ile çekişir.'],
['de052', 'Shakespeare\'in "Romeo ve Juliet" oyununda Mercutio kimin arkadaşıdır?', ['Juliet','Romeo','Tybalt','Benvolio'], 1, 'Mercutio, Romeo\'nun yakın arkadaşıdır.'],
['de053', 'Dante\'nin İlahi Komedya\'sında Araf\'ta bekleyenler kimlerdir?', ['Günahsızlar','Tövbe edememişler','Kâfirler','Şiddet suçluları'], 1, 'Araf, tövbe edememiş ruhların beklediği yerdir.'],
['de054', 'Tolstoy\'un "Anna Karenina" romanında Anna kiminle ilişki yaşar?', ['Karenin','Vronsky','Levin','Stiva'], 1, 'Anna, Kont Vronsky ile ilişki yaşar.'],
['de055', 'Dostoyevski\'nin "Karamazov Kardeşler" romanında kaç kardeş vardır?', ['İki','Üç','Dört','Beş'], 1, 'Üç kardeş: Dmitri, İvan ve Alyoşa.'],
['de056', 'Kafka\'nın "Şato" romanında K. ne yapmaya çalışır?', ['Şatoya girmek','Şatoyu satın almak','Şatoyu yıkmak','Şatoyu keşfetmek'], 0, 'K., şatoya girmeye çalışır.'],
['de057', 'Orwell\'in "1984" romanında "doublethink" nedir?', ['İki kez düşünmek','Aynı anda iki zıt şeyi kabul etmek','Derin düşünme','Hızlı düşünme'], 1, 'Doublethink, aynı anda iki zıddı kabul etmektir.'],
['de058', 'Robert Jordan hangi göreve atanır?', ['Köprüyü uçurmak','Düşmanı yok etmek','Mültecileri korumak','İstihbarat toplamak'], 0, 'Robert Jordan, köprüyü havaya uçurma görevini alır.'],
['de059', '"Yüzyıllık Yalnızlık" romanında kaç nesil anlatılır?', ['Üç','Dört','Yedi','On'], 2, 'Roman yedi nesli kapsar.'],
['de060', 'Sophokles\'in "Oedipus Kolonos\'ta" tragedyasında Oedipus nereye gider?', ['Teb\'e','Atina\'ya','Korint\'e','Sparta\'ya'], 1, 'Oedipus, Atina\'ya bağlı Kolonos\'a gider.'],
['de061', 'Shakespeare\'in "Antony and Cleopatra" oyununda Cleopatra hangi ülkenin kraliçesidir?', ['Yunanistan','Mısır','Persia','Roma'], 1, 'Cleopatra, Mısır kraliçesidir.'],
['de062', 'Dante\'nin İlahi Komedya\'sında Beatrice kimdir?', ['Dante\'nin eşi','Dante\'nin ilham perisi','Dante\'nin annesi','Dante\'nin kız kardeşi'], 1, 'Beatrice, Dante\'nin ilham perisidir.'],
['de063', 'Don Kişot\'unda Rocinante nedir?', ['Kılıç','At','Kalkan','Zırf'], 1, 'Rocinante, Don Kişot\'un atıdır.'],
['de064', 'Tolstoy\'un "Diriliş" romanında Nekhlyudov hangi sınıfın temsilcisidir?', ['Köylü','Asilzade','Tüccar','Memur'], 1, 'Nekhlyudov, asilzade sınıfından bir konttur.'],
['de065', '"Suç ve Ceza" romanında Sonia kimdir?', ['Raskolnikov\'un annesi','Sonia Marmeladova','Avdotya','Luzhin\'in karısı'], 1, 'Sonia, Raskolnikov\'un vicdan sesidir.'],
['de066', '"Dönüşüm" romanında Gregor\'un ailesi ona nasıl davranır?', ['Sevgiyle','İğrençlikle','Umursamazlıkla','Öfkeyle'], 1, 'Ailesi Gregor\'a iğrençlikle yaklaşır.'],
['de067', '"Hayvan Çiftliği" romanında "dört ayak iyi, iki ayak kötü" sloganı neyi temsil eder?', ['Hayvanların üstünlüğünü','İnsanların üstünlüğünü','Değişimi','İhtilali'], 0, 'Bu slogan hayvanların üstünlüğünü savunur.'],
['de068', '"Yaşlı Adam ve Deniz" romanında Santiago kaç gün denizde kalır?', ['İki','Üç','Dört','Beş'], 3, 'Santiago beş gün denizde kalır.'],
['de069', 'García Márquez hangi yıl Nobel Edebiyat Ödülü kazanmıştır?', ['1972','1982','1992','2002'], 1, 'García Márquez 1982\'de Nobel kazanmıştır.'],
['de070', '"Elektra" tragedyasında Orestes kimin oğludur?', ['Agamemnon','Aiskhylos','Kreon','Laios'], 0, 'Orestes, Agamemnon\'un oğludur.'],
['de071', '"Hamlet" oyununda Claudius kimin ölümünü düzenler?', ['Babasının','Kardeşinin','Hamlet\'in','Ophelia\'nın'], 1, 'Claudius, kardeşi eski kralı öldürür.'],
['de072', 'Dante\'nin İlahi Komedya\'sında Cehennemin kapısında ne yazar?', ['Giriş yasaktır','Biranızı terk edin','Buradan geri dönüş yok','Dikkatli olun'], 2, 'Kapıda "Buradan geri dönüş yok" yazar.'],
['de073', '"Savaş ve Barış" romanında Prens Andrei kimdir?', ['Napolyon\'un generali','Rus subayı','Fransız aristokrat','Avusturyalı diplomat'], 1, 'Prens Andrei, Rus ordusunda bir subaydır.'],
['de074', '"Suç ve Ceza" romanında Raskolnikov hangi eylemi işler?', ['Hırsızlık','Cinayet','Dolandırıcılık','Gasp'], 1, 'Raskolnikov, bir tefeci kadını ve kızını öldürür.'],
['de075', '"Dava" romanında avukat Titorelli ne vaat eder?', ['Adil bir dava','Beraat','Ömür boyu hapis','Yeni bir başlangıç'], 1, 'Titorelli beraat vaat eder ama imkansızdır.'],
['de076', '"1984" romanında Ministry of Truth ne iş yapar?', ['Gerçekliği tahrif etmek','Eğitim vermek','Sağlık hizmeti','Adalet dağıtma'], 0, 'Ministry of Truth, gerçekliği tahrif eder.'],
['de077', 'Hemingway\'in "Ardıl Güneş" romanı hangi konuyu işler?', ['İkinci Dünya Savaşı','İspanya İç Savaşı','Vietnam Savaşı','Kore Savaşı'], 0, 'Ardıl Güneş, İkinci Dünya Savaşı\'nı konu alır.'],
['de078', '"Kolera Günlerinde Aşk" romanı hangi yüzyılda geçer?', ['17.','18.','19.','20.'], 2, 'Roman 19. yüzyıl Kolombiya\'sında geçer.'],
['de079', '"Oedipus" tragedyasında Koryfe ne işlevi vardır?', ['Kral','Kahin','Başrahip','Savaşçı'], 1, 'Koryfe, Delphi kahinidir.'],
['de080', '"Macbeth" oyununda Macbeth hangi unvandadır?', ['Gener','Thane','Dük','Prens'], 1, 'Macbeth, Thane of Glamis\'tir.'],
['de081', 'Dante\'nin İlahi Komedya\'sında Limbo\'da hangi medeniyetin büyükleri vardır?', ['Roma','Yunan','Mısır','Mezopotamya'], 1, 'Limbo, Yunan ve Roma büyüklerinin bulunduğu yerdir.'],
['de082', '"Anna Karenina" romanında Levin hangi mesleği yapar?', ['Asker','Çiftçi','Avukat','Doktor'], 1, 'Levin, bir çiftçidir.'],
['de083', '"Suç ve Ceza" romanında Porfiry Petroviç kimdir?', ['Hakim','Savcı','Polis memuru','Avukat'], 2, 'Porfiry, cinayet soruşturmasını yürüten polistir.'],
['de084', '"Dönüşüm" romanında Gregor\'un kız kardeşi adı nedir?', ['Grete','Greta','Gisela','Gerda'], 0, 'Grete, Gregor\'un kız kardeşidir.'],
['de085', '"1984" romanında "Big Brother" neyi temsil eder?', ['Bir parti lideri','Devletin gözetlemesi','Bir televizyon kanalı','Bir din'], 1, 'Big Brother, devletin gözetlemesinin simgesidir.'],
['de086', '"Çanlar Kimin İçin Çalıyor" romanında María kimdir?', ['Partizan bir kadın','Bir köylü kızı','Bir öğretmen','Bir hemşire'], 0, 'María, partizan bir kadındır.'],
['de087', '"Kırmızı Pazartesi" romanı hangi konuyu işler?', ['Bir düğün','Bir cinayet','Bir devrim','Bir sel'], 1, 'Roman, Santiago Nasar\'ın öldürülmesini anlatır.'],
['de088', '"Filoktetes" tragedyasında Filoktetes hangi silahı taşır?', ['Kılıç','Yay','Mızrak','Balta'], 1, 'Filoktetes, zehirli bir yayın taşır.'],
['de089', '"Othello" oyununda Iago\'nun motivasyonu nedir?', ['Para','Güç','Kıskançlık','İntikam'], 2, 'Iago, kıskançlık ve nefretle hareket eder.'],
['de090', 'Dante\'nin İlahi Komedya\'sında Brunetto Latini Dante\'ye ne tavsiye eder?', ['Dönmek','Devam etmek','Yardım çağırmak','Dualar etmek'], 1, 'Brunetto, Dante\'ye yoluna devam etmesini söyler.'],
['de091', '"Diriliş" romanında Katyusha hangi suçla hüküm giyer?', ['Cinayet','Hırsızlık','Fuhuş','Zehirleme'], 0, 'Katyusha, bir adamı öldürmekle suçlanır.'],
['de092', '"Budala" romanında Nastasya Filippovna kimdir?', ['Bir kontes','Bir fahişe','Bir öğretmen','Bir hemşire'], 1, 'Nastasya, geçmişte istismara uğramış bir kadındır.'],
['de093', '"Dava" romanında mahkeme nerededir?', ['Sarayda','Bir apartmanda','Sokakta','Hapiste'], 1, 'Mahkeme, eski bir apartmanın çatı katındadır.'],
['de094', '"Hayvan Çiftliği" romanında Boxer hangi hayvandır?', ['İnek','At','Domuz','Koyun'], 1, 'Boxer, çalışkan bir attır.'],
['de095', '"Güneş de Doğar" romanında Jake Barnes hangi yaralanmaya sahiptir?', ['Bacak yaralanması','Görme kaybı','Cinsel organ yaralanması','Kol kaybı'], 2, 'Jake Barnes, savaşta cinsel organından yaralanmıştır.'],
['de096', '"Yüzyıllık Yalnızlık" romanında Macondo\'yu kim kurar?', ['Colonel Aureliano','José Arcadio Buendía','Úrsula','Melquíades'], 1, 'José Arcadio Buendía, Macondo\'yu kurar.'],
['de097', '"Oedipus" tragedyasında Teiresias kimdir?', ['Bir general','Kör bir kahin','Bir kral','Bir rahip'], 1, 'Teiresias, kör bir kahindir.'],
['de098', '"Bir Yaz Gecesi Rüyası" oyununda hangi varlıklar yer alır?', ['Periler','Cinler','Melekler','Devler'], 0, 'Oyun, perilerin dünyasını anlatır.'],
['de099', 'Dante\'nin İlahi Komedya\'sında Ulysses hangi hikayeyi anlatır?', ['Truva\'yı','Deniz yolculuğunu','Savaşı','Aşkını'], 1, 'Ulysses, deniz yolculuğunu anlatır.'],
['de100', 'Tolstoy\'un "İnsan Ne Yaşar" adlı eseri hangi türdedir?', ['Roman','Hikaye','Tiyatro','Şiir'], 1, 'İnsan Ne Yaşar, bir hikaye kitabıdır.'],
['de101', '"Ecinniler" romanında Stavrogin kimdir?', ['Bir devrimci','Bir asilzade','Bir papaz','Bir general'], 1, 'Stavrogin, soylu bir asilzadedir.'],
['de102', '"Büyük Duvar İnşaatı" hikayesinde duvar neyi temsil eder?', ['Güvenliği','İzolasyonu','Medeniyeti','Savaşı'], 1, 'Duvar, toplumsal izolasyonu temsil eder.'],
['de103', '"1984" romanında Winston Smith hangi bakanlıkta çalışır?', ['Truth','Peace','Love','Plenty'], 0, 'Winston, Ministry of Truth\'ta çalışır.'],
['de104', '"Beyaz Taşlı Bahçe" romanı hangi konuyu işler?', ['Savaş','Aşk','Göç','Devrim'], 1, 'Roman, bir aşk hikayesini anlatır.'],
['de105', '"Büyük Definede Kral" hangi türdedir?', ['Roman','Hikaye','Deneme','Şiir'], 1, 'Kısa hikayelerden oluşan bir kitaptır.'],
['de106', '"Electra" tragedyasında Electra kimin için yas tutar?', ['Annesi','Babası','Kardeşi','Kocası'], 1, 'Electra, babası Agamemnon için yas tutar.'],
['de107', '"Julius Caesar" oyununda Brutus neden Sezar\'ı öldürür?', ['Kişisel nefret','Devlet için','Para için','İntikam için'], 1, 'Brutus, Roma cumhuriyetini korumak için öldürür.'],
['de108', 'Dante\'nin İlahi Komedya\'sında Francesca da Rimini hangi günahın cezasını çeker?', ['Hırsızlık','Zina','Gurur','Öfke'], 1, 'Francesca, zina günahının cezasını çeker.'],
['de109', '"Savaş ve Barış" romanında Kutuzov kimdir?', ['Rus generali','Fransız generali','Avusturya generali','Prusya generali'], 0, 'Kutuzov, Rus ordusunun başkomutanıdır.'],
['de110', '"Suç ve Ceza" romanında Luzhin kimdir?', ['Raskolnikov\'un arkadaşı','Avdotya\'nın nişanlısı','Bir avukat','Bir polis'], 1, 'Luzhin, Avdotya\'nın nişanlısıdır.'],
['de111', '"Dönüşüm" romanında Gregor hangi şirkette çalışır?', ['Tekstil','Gıda','İpek','Banka'], 2, 'Gregor, bir ipek firmasında çalışır.'],
['de112', '"1984" romanında "telescreen" nedir?', ['Bir televizyon','Hem görüntü alıp veren ekran','Bir bilgisayar','Bir telefon'], 1, 'Telescreen, çift taraflı görüntü cihazıdır.'],
['de113', '"Veda Silahı" romanı hangi savaşı konu alır?', ['Birinci Dünya Savaşı','İkinci Dünya Savaşı','İspanya İç Savaşı','Vietnam'], 0, 'Veda Silahı, Birinci Dünya Savaşı\'nı anlatır.'],
['de114', '"Yüzyıllık Yalnızlık" romanında Melquíades kimdir?', ['Bir keşiş','Bir Çingene bilge','Bir asker','Bir tüccar'], 1, 'Melquíades, bilge bir Çingenendir.'],
['de115', '"Oedipus" tragedyasında Oedipus kendini nasıl cezalandırır?', ['Sürgüne gider','Gözlerini kör eder','Öldürür','Hapse girer'], 1, 'Oedipus, gözlerini kör eder.'],
['de116', '"Kral Lear" oyununda Gloucester hangi acıyı yaşar?', ['Oğlunun ölümü','Gözlerinin kör edilmesi','Kızının ihaneti','Soyunun tükenmesi'], 1, 'Gloucester\'ın gözleri kör edilir.'],
['de117', 'Dante\'nin İlahi Komedya\'sında Ulysses neden cehennemde ceza çeker?', ['Hırsızlık','Aldatmaca','Cinayet','Gurur'], 1, 'Ulysses, aldatmaca nedeniyle ceza çeker.'],
['de118', '"Anna Karenina" romanında Anna\'nın kocası kimdir?', ['Vronsky','Levin','Alexey Karenin','Stiva'], 2, 'Alexey Karenin, Anna\'nın kocasıdır.'],
['de119', '"Karamazov Kardeşler" romanında baba Karamazov kimdir?', ['Fyodor','Dmitri','İvan','Alyoşa'], 0, 'Fyodor, üç kardeşin babasıdır.'],
['de120', '"Dava" romanında Josef K. romanın sonunda ne olur?', ['Beraat eder','Hapse girer','Öldürülür','Kaçar'], 2, 'Josef K. öldürülür.'],
['de121', '"1984" romanında "Room 101" nedir?', ['Bir oda','İşkence odası','Bir hapishane','Bir ofis'], 1, 'Room 101, işkence odasıdır.'],
['de122', '"Yaşlı Adam ve Deniz" romanında devasa balık hangi türdendir?', ['Balina','Orkinos','Kılıç balığı','Marlin'], 3, 'Devasa balık bir marlintir.'],
['de123', '"Kolera Günlerinde Aşk" romanında Florentino Ariza kimdir?', ['Bir kaptan','Bir postacı','Bir tüccar','Bir öğretmen'], 1, 'Florentino, posta şirketinde çalışır.'],
['de124', '"Oedipus" tragedyasında Oedipus\'un annesi ve karısı aynı kişidir. Kimdir?', ['Antigone','Jokasta','Electra','Ismene'], 1, 'Jokasta, hem annesi hem karısıdır.'],
['de125', '"Venedik Tüccarı" oyununda Shylock hangi dinden bir karakterdir?', ['Müslüman','Hristiyan','Yahudi','Budist'], 2, 'Shylock, bir Yahudi tüccarıdır.'],
['de126', 'Dante\'nin İlahi Komedya\'sında Cehennemde kaç halka vardır?', ['Dokuz','On','On bir','On iki'], 0, 'Cehennemde dokuz halka vardır.'],
['de127', '"Savaş ve Barış" romanında Natalya Rostova kimdir?', ['Bir prenses','Bir kontes','Bir asilzade kızı','Bir köylü'], 2, 'Natalya, asil bir aileden gelen genç bir kızdır.'],
['de128', '"Suç ve Ceza" romanında Raskolnikov\'un annesi adı nedir?', ['Sonia','Pulcheria','Avdotya','Katerina'], 1, 'Pulcheria, Raskolnikov\'un annesidir.'],
['de129', '"Dönüşüm" romanında Gregor ailesine nasıl bakar?', ['Ailesini işe gönderir','Ailesini doyurur','Ailesini giydirir','Ailesini eğitir'], 1, 'Gregor, ailesinin geçimini sağlar.'],
['de130', '"Hayvan Çiftliği" romanında Benjamin hangi hayvandır?', ['İnek','Eşek','Koyun','At'], 1, 'Benjamin, bir eşekdir.'],
['de131', '"Güneş de Doğar" romanında Brett Ashley kimdir?', ['Bir prenses','Bir kontes','Bir avukat','Bir İngiliz soylusu'], 3, 'Brett Ashley, İngiliz soylusudur.'],
['de132', '"Yüzyıllık Yalnızlık" romanında Colonel Aureliano kaç savaşa katılır?', ['On','Yirmi','Otuz','Kırk'], 2, 'Colonel otuz iki ayaklanmaya katılır.'],
['de133', '"Antigone" tragedyasında Antigone kimin emrine karşı gelir?', ['Babasının','Erkek kardeşinin','Kral Kreon\'un','Tanrıların'], 2, 'Antigone, Kreon\'un emrine karşı gelir.'],
['de134', '"Hamlet" oyununda Hamlet\'in annesi kimdir?', ['Ophelia','Gertrude','Cordelia','Lady Macbeth'], 1, 'Gertrude, Hamlet\'in annesidir.'],
['de135', 'Dante\'nin İlahi Komedya\'sında Virgilius hangi dönem şairidir?', ['Rönesans','Orta Çağ','Antik Çağ','Modern'], 2, 'Virgilius, Antik Roma şairidir.'],
['de136', '"Anna Karenina" romanında Levin hangi arayışın içindedir?', ['Ateizm','Maneviyat','Varoluşçuluk','Nihilizm'], 1, 'Levin, manevi bir arayış içindedir.'],
['de137', '"Budala" romanında Myshkin hangi hastalıktan muzdariptir?', ['Verem','Epilepsi','Kan kanseri','Şizofreni'], 1, 'Myshkin, epilepsi hastasıdır.'],
['de138', '"Dava" romanında davası ne kadar sürer?', ['Bir hafta','Bir ay','Bir yıl','Süresiz'], 3, 'Dava, süresiz ve belirsizdir.'],
['de139', '"1984" romanında Julia kimdir?', ['Bir polis','Bir devlet memuru','Bir Parti üyesi','Bir direnişçi'], 3, 'Julia, gizli bir direnişçidir.'],
['de140', '"Çanlar Kimin İçin Çalıyor" romanında Pilar kimdir?', ['Bir hemşire','Bir köylü kadını','Bir partizan','Bir öğretmen'], 2, 'Pilar, partizanların güçlü bir kadınıdır.'],
['de141', '"Yüzyıllık Yalnızlık" romanında Remedios güzeli nasıl kaybolur?', ['Hastalık','Kaza','Gökyüzüne yükselmek','Zehirlenme'], 2, 'Remedios gökyüzüne yükselerek kaybolur.'],
['de142', '"Oedipus" tragedyasında Oedipus\'un gerçek kimliğini kim açıklar?', ['Bir kahin','Bir çoban','Bir köle','Bir general'], 1, 'Bir çoban, gerçek kimliği açıklar.'],
['de143', '"Romeo ve Juliet" oyununda Friar Laurence Romeo\'ya ne yapar?', ['Evlilik töreni yapar','Zehir verir','Öğüt verir','Sığınak sağlar'], 0, 'Friar Laurence, gizlice evlendirir.'],
['de144', 'Dante\'nin İlahi Komedya\'sında Cennette kaç katman vardır?', ['Yedi','Dokuz','On','On iki'], 1, 'Cennette dokuz katman vardır.'],
['de145', '"Savaş ve Barış" romanında Pierre Bezukhov kimdir?', ['Bir general','Bir asilzade','Bir tüccar','Bir diplomat'], 1, 'Pierre, zengin bir asilzadedir.'],
['de146', '"Suç ve Ceza" romanında Sonya neden fuhuş yapar?', ['Ailesini geçindirmek','Lüks yaşam','İntikam','Zevk için'], 0, 'Sonya, ailesini geçindirmek için yapar.'],
['de147', '"Dönüşüm" romanında Gregor\'un odasının kapısı ne zaman açılır?', ['Sabahtan','Öğleden sonra','Akşam','Gece'], 1, 'Kapı, öğleden sonra açılır.'],
['de148', '"Hayvan Çiftliği" romanında Snowball hangi hayvandır?', ['At','Domuz','İnek','Köpek'], 1, 'Snowball, devrimci bir domuzdur.'],
['de149', '"Yaşlı Adam ve Deniz" romanında Manolin kimdir?', ['Santiago\'nun oğlu','Santiago\'nun çırağı','Bir balıkçı','Bir tüccar'], 1, 'Manolin, Santiago\'nun çırağıdır.'],
['de150', '"Kırmızı Pazartesi" romanı hangi dilde yazılmıştır?', ['Portekizce','İspanyolca','İngilizce','Fransızca'], 1, 'Roman İspanyolca yazılmıştır.'],
];
ky.forEach(d => L.push(q(d[0],d[1],d[2],d[3],'kolay',d[4])));

// Now save what we have and we'll add more via a second script
L.push("");
L.push("];");
L.push("");

fs.writeFileSync(path, L.join('\n'), 'utf8');
console.log('Part 1 written: ' + L.length + ' lines');
